routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("php_info",function(){
    phpinfo();
});
Route::namespace("\App\Http\Controllers")->prefix("user")->as("user.")
    ->group(function () {
        //User routes
        Route::get("createUser", "UserController@create")->name("user.create");
        Route::get("userList", "UserController@index")->name("user.list");
    });

Route::namespace("\App\Http\Controllers\Back")->prefix("superadmin")->as("superadmin.")
    ->group(function (){
        route::resource('charities', 'CharityController');
        Route::get("createAdminCharityUser","CharityController@createAdminCharityUser")->name("charities.createAdminCharityUser");
        Route::post("storeAdminCharityUser","CharityController@storeAdminCharityUser")->name("charities.storeAdminCharityUser");
    });

Route::namespace("\App\Http\Controllers\Back")->prefix("admin")->as("admin.")
    ->group(function () {

        //User routes
        Route::get("createUser", "UserController@create")->name("user.create");
        Route::get("userList", "UserController@index")->name("user.list");

        //Dashboard routes
        Route::get("/", "DashboardController@index")->name("dashboard.index");

        //Madadjoo routes
        route::resource('madadjoos', 'MadadjooController');

        //Needs routes
        route::resource('needs', 'NeedsController');

        // Categories routes
        route::resource('categories','CategoriesController');

//        search-madadjoo-in-create-need-form
        Route::get('select2-search-madadjoo', 'MadadjooController@select2SearchMadadjoo');


    });

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'UserController@index');
/*Route::get('/madadjooform', 'MadadjooController@index');
Route::post('/storemadadjoo', 'MadadjooController@store')->name("storemadadjoo");*/

app/Models/Madadjoo.php
<?php

namespace App\Models;

use Hekmatinasser\Verta\Verta;
use Illuminate\Database\Eloquent\Model;
use Baloot\EloquentHelper;

class Madadjoo extends Model
{
    use EloquentHelper;
    const USER_TYPE = 4;// مددجو
    protected $table = "users";

    public function needs()
    {
        return $this->hasMany(Needs::class);
    }

    public function getGenderMadadjooAttribute()
    {
        return $this["gender"] == 1 ? "زن" : "مرد";
    }

    public function setBirthdayAttribute($value)
    {
        $jalali = Verta::parseFormat("Y/m/d", $value)->addDays(2);
        $this->attributes["birthday"] = $jalali->formatGregorian("Y-m-d 00:00:00");
    }


    protected $casts = [
        "birthday" => "date"
    ];

    public function scopeMadadjoo($query)
    {
        return $query->whereType(4);
    }


}

app/Http/Controllers/Back/CategoriesController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Categories::get()->where("id_charity",Auth::user()->id_charity);
        return view('back.categories.form',compact('categories'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            "categoryname"=>"required|unique:categories"
        ]);
        $category = new Categories();
        $category->charity_id = Auth::user()->charity_id;
        $category->categoryname = $request->categoryname;
        $category->save();
        $categories = Categories::get()->where("id_charity",Auth::user()->id_charity);
        return view('back.categories.form',compact('categories'));

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show(Categories $categories)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit(Categories $categories)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categories $categories)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categories $categories)
    {
        //
    }
}

app/Http/Controllers/Back/CharityController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Charity;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CharityController extends Controller
{
    public function index()
    {
        $charities = Charity::paginate(10);
        return view("back.superadmin.charity",compact('charities'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $this->validate($request,[
           "name"=>"required",
            "tell"=>"iran_phone",
        ]);
        $charity = new Charity();
        $charity->name = $request->name;
        $charity->tell = $request->tell;
        $charity->address = $request->address;
        $charity->save();
        return self::redirectWithSuccess(route('superadmin.charities.index'),'ثبت با موفقیت انجام شد');
        //
    }

    public function show(Charity $charity)
    {
        //
    }

    public function edit(Charity $charity)
    {
        //
    }

    public function update(Request $request, Charity $charity)
    {
        //
    }

    public function destroy(Charity $charity)
    {
        //
    }

    public function createAdminCharityUser(){

        $charities = Charity::get();
        $collection = collect($charities);
        $charitiesKey = $collection->mapWithKeys(function ($item){
           return [$item['id']=>$item['name']];
        });
        $users = User::get()->where("type","2");
        return view('back.superadmin.charityAdminUser',compact('charitiesKey','users'));
    }
    public function storeAdminCharityUser(Request $request){
        $this->validate($request, [
            "name" => "required",
            "national_code" => "required|unique:users|min:10|max:10",
            "mobile" => 'iran_mobile',
            "email" => "required|unique:users",
            "user_name" => "required|unique:users",
            'password' => "required|min:6|confirmed",
        ]);
        $user = new User();
        $user->email = $request->email;
        $user->charity_id = $request->charity_id;
        $user->type = config('app.CHARITY_ADMIN_USER');
        $user->name = $request->name;
        $user->national_code = $request->national_code;
        $user->user_name = $request->user_name;
        $user->password = Hash::make($request->password);
        $user->mobile = $request->mobile;
        $user->address = $request->address;
        $user->save();
        $users = User::get()->where("type","2");
        return self::redirectWithSuccess(route('superadmin.charities.createAdminCharityUser'), 'ثبت با موفقیت انجام شد',compact('users'));
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\Dashboard;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("back.dashboard.dashboard");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function show(Dashboard $dashboard)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function edit(Dashboard $dashboard)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dashboard $dashboard)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dashboard $dashboard)
    {
        //
    }
}

app/Http/Controllers/Back/MadadjooController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\Madadjoo;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use League\Flysystem\Config;
use Hekmatinasser\Verta;

class MadadjooController extends Controller
{
    public function index()
    {
        $charity_id = Auth::user()->charity_id;
        $madadjoos = Madadjoo::where("type","4")->where('charity_id',$charity_id)->paginate(10);
        return view('back.madadjoos.all', compact('madadjoos'));
    }

    public function create()
    {
        return view("back.madadjoos.create");
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required",
            "national_code" => "required|unique:users|min:10|max:10",
            "mobile" => 'iran_mobile',
            "address" => "required",
        ]);
        $madadjoo = new Madadjoo;
        $madadjoo->charity_id = Auth::user()->charity_id;
        $madadjoo->city_id = $request->city_id;
        $madadjoo->type = Madadjoo::USER_TYPE;
        $madadjoo->name = $request->name;
        $madadjoo->national_code = $request->national_code;
        $madadjoo->family_members = $request->family_members;
        $madadjoo->gender = $request->gender;
        $madadjoo->birthday = $request->birthday;
//        dd(Verta\Verta::getGregorian(1394,10,4));
        $madadjoo->mobile = $request->mobile;
        $madadjoo->tell = $request->tell;
        $madadjoo->address = $request->address;
        $madadjoo->save();
        return self::redirectWithSuccess(route('admin.madadjoos.create'), 'ثبت با موفقیت انجام شد');
    }


    public function show(Madadjoo $madadjoo)
    {
        $needs=$madadjoo->needs()->get();
        return view('back.madadjoos.show', compact('needs','madadjoo'));

    }


    public function edit(Madadjoo $madadjoo)
    {
        //
    }


    public function update(Request $request, Madadjoo $madadjoo)
    {
        //
    }


    public function destroy(Madadjoo $madadjoo)
    {
        //
    }

    public function select2SearchMadadjoo(Request $request)
    {
        $data = [];
            $search = $request->q;
            $data =Madadjoo::where('name','LIKE',"%$search%")
                ->orwhere('national_code','LIKE',"%$search%")
                ->madadjoo()
                ->limit(20)
                ->get();
        return response()->json($data);
    }
}

app/Http/Controllers/Back/NeedsController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\Needs;
use Illuminate\Http\Request;

class NeedsController extends Controller
{
    public function index()
    {
        return view("back.needs.list");
    }

    public function create()
    {
        return view("back.needs.create");
    }

    public function store(Request $request)
    {
        //
    }


    public function show(Needs $needs)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\Needs  $needs
     * @return \Illuminate\Http\Response
     */
    public function edit(Needs $needs)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\Needs  $needs
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Needs $needs)
    {
        //
    }
    public function categoryForm(){
        return view("back.needs.categories");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\Needs  $needs
     * @return \Illuminate\Http\Response
     */
    public function destroy(Needs $needs)
    {
        //
    }
}

app/Http/Controllers/Back/ResponsibleCharityController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\ResponsibleCharity;
use Illuminate\Http\Request;

class ResponsibleCharityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function show(ResponsibleCharity $responsibleCharity)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function edit(ResponsibleCharity $responsibleCharity)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ResponsibleCharity $responsibleCharity)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function destroy(ResponsibleCharity $responsibleCharity)
    {
        //
    }
}

app/Http/Controllers/Back/UserController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    //
}

resources/views/back/madadjoos/all.blade.php
@extends('back.layout.app')
@section('title','لیست مددجو')
@section('content')
    <x-success></x-success>
    {{$madadjoos->render()}}
    <div class="card">
        <div class="card-body">
            <table class="table">
                <thead>
                <tr>
                    <th></th>
                    <th>نام و نام خانوادگی</th>
                    <th>کد ملی</th>
                    <th>تعداد اعضای خانوار</th>
                    <th>شماره همراه</th>
                    <th>آدرس</th>
                </tr>
                </thead>
                <tbody>
                @foreach($madadjoos as $madadjoo)
                    <tr>
                        <td></td>
                        <td><a href="{{route('admin.madadjoos.show',$madadjoo)}}" >{{ $madadjoo->name }}</a></td>
                        <td class="text-left">{{ $madadjoo->national_code }}</td>
                        <td>{{ $madadjoo->family_members }}</td>
                        <td>{{ $madadjoo->mobile }}</td>
                        <td>{{ $madadjoo->address }}</td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection

resources/views/back/madadjoos/create.blade.php
@extends('back.layout.app')
@section('title','اضافه کردن مددجو')
@section('content')
    <x-success></x-success>
    <form action="{{route('admin.madadjoos.store')}}"
          method="post" enctype="multipart/form-data">
        @csrf
        <div class="col-md-12">
            <div class="card">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            {{
                                Html::text("name")
                                ->value(old("name"))
                                ->label("نام و نام خانوادگی :")
                            }}
                        </div>
                        <div class="col-md-4">
                            {{
                                Html::text("national_code")
                                ->value(old("national_code"))
                                ->label("کد ملی:")
                            }}
                        </div>
                        <div class="col-md-4">
                            {{
                                Html::select("family_members")
                                    ->label("تعداد اعضای خانوار:")
                                    ->value("1")
                                    ->description("")
                                    ->select_options([
                                    "1"=>"1",
                                    "2"=>"2",
                                    "3"=>"3",
                                    "4"=>"4",
                                    "5"=>"5",
                                    "6"=>"6"])
                                }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{
                            Html::select("gender")
                                ->label("جنسیت:")
                                ->value("1")
                                ->description("")
                                ->select_options([
                                "1"=>"زن",
                                "2"=>"مرد"])
                            }}
                        </div>
                        <div class="col-md-4">
                            {{
                                Html::text("birthday")
                                ->value(old("birthday"))
                                ->label("تاریخ تولد:")
                            }}
                        </div>
                        <div class="col-md-4">
                            {{
                                Html::text("mobile")
                                ->value(old("mobile"))
                                ->label("تلفن همراه :")
                            }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            {{
                                Html::text("tell")
                                ->value(old("tell"))
                                ->label("تلفن:")
                            }}
                        </div>
                        <div class="col-md-4">
                            {{
                               Html::select("city_id")
                                ->label("شهر:")
                                ->value("1")
                                ->description("")
                                ->select_options([
                                "1"=>"مشهد",
                                "2"=>"سایر"])
                            }}

                        </div>
                        <div class="col-md-4">
                            {{
                                Html::text("address")
                                ->value(old("address"))
                                ->label("آدرس:")
                            }}
                        </div>
                    </div>
                    <div class="row">

                        <div class="col-md-4">
                            <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                        </div>

                    </div>
                </div>
                <div class="row">

                </div>
            </div>
        </div>

        </div>
    </form>
@stop

resources/views/back/madadjoos/show.blade.php
@extends('back.layout.app')
@section('title','اطلاعات مددجو')
@section('content')
    <x-success></x-success>
    <div class="row">
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>مشخصات مددجو</strong>
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-2 col-4 col-xs-offset-3 col-lg-4 col-xl-2">
                            <img src="/images/avatar-placeholder.png" alt="" class="w-100 rounded-circle">
                        </div>
                        <div class="col-md-10 col-lg-8 col-xl-10">
                            <div class="text-success h4"><i class="fa fa-user"></i> {{ $madadjoo->name }} </div>
                            {{Html::info()->value($madadjoo->national_code)->label("- کد ملی ") }}
                            {{Html::info()->value($madadjoo->family_members)->label("- تعداد اعضای خانواده (نفر) ") }}
                            {{Html::info()->value($madadjoo->gender_madadjoo)->label("- جنسیت ") }}
                            {{Html::info()->value($madadjoo->birthday_fa_f)->label("- تاریخ تولد ") }}
                            {{Html::info()->value($madadjoo->mobile)->label("- شماره همراه ") }}
                            {{Html::info()->value($madadjoo->tell)->label("- تلفن ") }}
                            {{Html::info()->value($madadjoo->address)->label("- آدرس ") }}

                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> ویرایش مشخصات </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card">
                <div class="card-header">
                    <strong>نیاز های ثبت شده برای مددجو</strong>
                </div>
                <div class="card-body">
                        <table class="table">
                            <thead>
                            <tr>
                                <th></th>
                                <th>ردیف</th>
                                <th>عنوان</th>
                                <th>اعتبار مورد نیاز</th>
                                <th>وضعیت</th>
                                <th>رزرو</th>
                                <th>رزرو</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach($needs as $need)
                                <tr>
                                    <td></td>
                                    <td>{{$loop->iteration }}</td>
                                    <td>{{$need->title}}</td>
                                    <td>{{$need->price}}</td>
                                    <td>{{$need->status}}</td>
                                    <td>گزارش واریز</td>
                                    <td>ویرایش</td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> دکمه رزرو</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>کمک های جمع آوری شده برای نیاز : </strong>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th></th>
                            <th>ردیف</th>
                            <th>نام و نام خانوادگی خیر</th>
                            <th>مبلغ کمک شده</th>
                            <th>تاریخ</th>
                            <th>ساعت</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($needs as $need)
                            <tr>
                                <td></td>
                                <td>{{$loop->iteration }}</td>
                                <td>{{$need->title}}</td>
                                <td>{{$need->price}}</td>
                                <td>__/__/____</td>
                                <td>..:..</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> خروجی اکسل</a>
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> چاپ</a>

                    </div>
                </div>
            </div>
        </div>

    </div>


@endsection