routes/web.php
<?php

use Illuminate\Support\Facades\Route;

Route::get("php_info",function(){
    phpinfo();
});
Route::namespace("\App\Http\Controllers")->prefix("user")->as("user.")
    ->group(function () {
        //User routes
        Route::get("createUser", "UserController@create")->name("user.create");
        Route::get("userList", "UserController@index")->name("user.list");
    });

Route::namespace("\App\Http\Controllers\Back")->prefix("superadmin")->as("superadmin.")
    ->group(function (){
        route::resource('charities', 'CharityController');
        Route::get("createAdminCharityUser","CharityController@createAdminCharityUser")->name("charities.createAdminCharityUser");
        Route::post("storeAdminCharityUser","CharityController@storeAdminCharityUser")->name("charities.storeAdminCharityUser");
    });

Route::namespace("\App\Http\Controllers\Back")->prefix("admin")->as("admin.")
    ->group(function () {

        //User routes
        Route::get("createUser", "UserController@create")->name("user.create");
        Route::get("userList", "UserController@index")->name("user.list");

        //Dashboard routes
        Route::get("/", "DashboardController@index")->name("dashboard.index");

        //Madadjoo routes
        route::resource('madadjoos', 'MadadjooController');

        //Needs routes
        route::resource('needs', 'NeedsController');

        // Categories routes
        route::resource('categories','CategoriesController');

//        search-madadjoo-in-create-need-form
        Route::get('select2-search-madadjoo', 'MadadjooController@select2SearchMadadjoo');


    });

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');
Route::get('/user', 'UserController@index');
/*Route::get('/madadjooform', 'MadadjooController@index');
Route::post('/storemadadjoo', 'MadadjooController@store')->name("storemadadjoo");*/

app/Http/Controllers/Back/CategoriesController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Categories;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Categories::get()->where("id_charity",Auth::user()->id_charity);
        return view('back.categories.form',compact('categories'));
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            "categoryname"=>"required|unique:categories"
        ]);
        $category = new Categories();
        $category->charity_id = Auth::user()->charity_id;
        $category->categoryname = $request->categoryname;
        $category->save();
        $categories = Categories::get()->where("id_charity",Auth::user()->id_charity);
        return view('back.categories.form',compact('categories'));

        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function show(Categories $categories)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function edit(Categories $categories)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Categories $categories)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Categories  $categories
     * @return \Illuminate\Http\Response
     */
    public function destroy(Categories $categories)
    {
        //
    }
}

app/Http/Controllers/Back/CharityController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\Models\Charity;
use App\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Hash;

class CharityController extends Controller
{
    public function index()
    {
        $charities = Charity::paginate(10);
        return view("back.superadmin.charity",compact('charities'));
    }

    public function create()
    {
        //
    }

    public function store(Request $request)
    {
        $this->validate($request,[
           "name"=>"required",
            "tell"=>"iran_phone",
        ]);
        $charity = new Charity();
        $charity->name = $request->name;
        $charity->tell = $request->tell;
        $charity->address = $request->address;
        $charity->save();
        return self::redirectWithSuccess(route('superadmin.charities.index'),'ثبت با موفقیت انجام شد');
        //
    }

    public function show(Charity $charity)
    {
        //
    }

    public function edit(Charity $charity)
    {
        //
    }

    public function update(Request $request, Charity $charity)
    {
        //
    }

    public function destroy(Charity $charity)
    {
        //
    }

    public function createAdminCharityUser(){

        $charities = Charity::get();
        $collection = collect($charities);
        $charitiesKey = $collection->mapWithKeys(function ($item){
           return [$item['id']=>$item['name']];
        });
        $users = User::get()->where("type","2");
        return view('back.superadmin.charityAdminUser',compact('charitiesKey','users'));
    }
    public function storeAdminCharityUser(Request $request){
        $this->validate($request, [
            "name" => "required",
            "national_code" => "required|unique:users|min:10|max:10",
            "mobile" => 'iran_mobile',
            "email" => "required|unique:users",
            "user_name" => "required|unique:users",
            'password' => "required|min:6|confirmed",
        ]);
        $user = new User();
        $user->email = $request->email;
        $user->charity_id = $request->charity_id;
        $user->type = config('app.CHARITY_ADMIN_USER');
        $user->name = $request->name;
        $user->national_code = $request->national_code;
        $user->user_name = $request->user_name;
        $user->password = Hash::make($request->password);
        $user->mobile = $request->mobile;
        $user->address = $request->address;
        $user->save();
        $users = User::get()->where("type","2");
        return self::redirectWithSuccess(route('superadmin.charities.createAdminCharityUser'), 'ثبت با موفقیت انجام شد',compact('users'));
    }
}

app/Http/Controllers/Back/DashboardController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\Dashboard;
use Illuminate\Http\Request;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view("back.dashboard.dashboard");
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function show(Dashboard $dashboard)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function edit(Dashboard $dashboard)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Dashboard $dashboard)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\Dashboard  $dashboard
     * @return \Illuminate\Http\Response
     */
    public function destroy(Dashboard $dashboard)
    {
        //
    }
}

app/Http/Controllers/Back/MadadjooController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\Madadjoo;
use Illuminate\Foundation\Auth\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use League\Flysystem\Config;
use Hekmatinasser\Verta;

class MadadjooController extends Controller
{
    public function index()
    {
        $charity_id = Auth::user()->charity_id;
        $madadjoos = Madadjoo::where("type","4")->where('charity_id',$charity_id)->paginate(10);
        return view('back.madadjoos.all', compact('madadjoos'));
    }

    public function create()
    {
        return view("back.madadjoos.create");
    }


    public function store(Request $request)
    {
        $this->validate($request, [
            "name" => "required",
            "national_code" => "required|unique:users|min:10|max:10",
            "mobile" => 'iran_mobile',
            "address" => "required",
        ]);
        $madadjoo = new Madadjoo;
        $madadjoo->charity_id = Auth::user()->charity_id;
        $madadjoo->city_id = $request->city_id;
        $madadjoo->type = Madadjoo::USER_TYPE;
        $madadjoo->name = $request->name;
        $madadjoo->national_code = $request->national_code;
        $madadjoo->family_members = $request->family_members;
        $madadjoo->gender = $request->gender;
        $madadjoo->birthday = $request->birthday;
//        dd(Verta\Verta::getGregorian(1394,10,4));
        $madadjoo->mobile = $request->mobile;
        $madadjoo->tell = $request->tell;
        $madadjoo->address = $request->address;
        $madadjoo->save();
        return self::redirectWithSuccess(route('admin.madadjoos.create'), 'ثبت با موفقیت انجام شد');
    }


    public function show(Madadjoo $madadjoo)
    {
        $needs=$madadjoo->needs()->get();
        return view('back.madadjoos.show', compact('needs','madadjoo'));

    }


    public function edit(Madadjoo $madadjoo)
    {
        //
    }


    public function update(Request $request, Madadjoo $madadjoo)
    {
        //
    }


    public function destroy(Madadjoo $madadjoo)
    {
        //
    }

    public function select2SearchMadadjoo(Request $request)
    {
        $data = [];
            $search = $request->q;
            $data =Madadjoo::where('name','LIKE',"%$search%")
                ->orwhere('national_code','LIKE',"%$search%")
                ->madadjoo()
                ->limit(20)
                ->get();
        return response()->json($data);
    }
}

app/Http/Controllers/Back/NeedsController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\Needs;
use Illuminate\Http\Request;

class NeedsController extends Controller
{
    public function index()
    {
        return view("back.needs.list");
    }

    public function create()
    {
        return view("back.needs.create");
    }

    public function store(Request $request)
    {
        //
    }


    public function show(Needs $needs)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\Needs  $needs
     * @return \Illuminate\Http\Response
     */
    public function edit(Needs $needs)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\Needs  $needs
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Needs $needs)
    {
        //
    }
    public function categoryForm(){
        return view("back.needs.categories");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\Needs  $needs
     * @return \Illuminate\Http\Response
     */
    public function destroy(Needs $needs)
    {
        //
    }
}

app/Http/Controllers/Back/ResponsibleCharityController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use App\models\ResponsibleCharity;
use Illuminate\Http\Request;

class ResponsibleCharityController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function show(ResponsibleCharity $responsibleCharity)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function edit(ResponsibleCharity $responsibleCharity)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ResponsibleCharity $responsibleCharity)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\ResponsibleCharity  $responsibleCharity
     * @return \Illuminate\Http\Response
     */
    public function destroy(ResponsibleCharity $responsibleCharity)
    {
        //
    }
}

app/Http/Controllers/Back/UserController.php
<?php

namespace App\Http\Controllers\Back;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class UserController extends Controller
{
    //
}

resources/views/back/superadmin/charity.blade.php
@extends('back.layout.app')
@section('title','داشبورد سوپر ادمین')
@section('content')
    <x-success></x-success>
    <div class="row">
        <div class="col-md-12">
            <form action="{{route('superadmin.charities.store')}}"
                  method="post" enctype="multipart/form-data">
                @csrf
                <div class="card">
                    <div class="card-header">
                        <strong>ثبت مرکز نیکوکاری</strong>
                    </div>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-4">
                                {{
                                    Html::text("name")
                                    ->value(old("name"))
                                    ->label("نام مرکز نیکوکاری :")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("tell")
                                    ->value(old("tell"))
                                    ->label("تلفن:")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("address")
                                    ->value(old("address"))
                                    ->label("آدرس:")
                                }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-left">
                            <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>لیست مراکز نیکوکاری ثبت شده : </strong>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th></th>
                            <th>ردیف</th>
                            <th>نام مرکز نیکوکاری</th>
                            <th>تلفن</th>
                            <th>آدرس</th>
                            <th>وضعیت</th>
                            <th>حذف</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($charities as $charity)
                            <tr>
                                <td></td>
                                <td>{{$loop->iteration }}</td>
                                <td>{{$charity->name}}</td>
                                <td>{{$charity->tell}}</td>
                                <td>{{$charity->address}}</td>
                                <td>فعال/غیرفعال</td>
                                <td>حذف</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> خروجی اکسل</a>
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> چاپ</a>

                    </div>
                </div>
            </div>
        </div>

    </div>

@stop

resources/views/back/superadmin/charityAdminUser.blade.php
@extends('back.layout.app')
@section('title','داشبورد سوپر ادمین')
@section('content')
    <x-success></x-success>
    <div class="row">
        <div class="col-md-12">
            <form action="{{route('superadmin.charities.storeAdminCharityUser')}}"
                  method="post" enctype="multipart/form-data">
                {{ Html::hidden()->name('user_type')->value(config('app.CHARITY_ADMIN_USER')) }}

                @csrf
                <div class="card">
                    <div class="card-header">
                        <strong>تعریف کاربر مدیر مرکز نیکوکاری</strong>
                    </div>
                    <div class="card-body">

                        <div class="row">
                            <div class="col-md-4">
                                {{
                                    Html::select("charity_id")
                                        ->label("نام مرکز نیکوکاری:")
                                        ->value(old("charity_id"))
                                        ->description("")
                                        ->select_options($charitiesKey)
                                    }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("name")
                                    ->value(old("name"))
                                    ->label("نام و نام خانوادگی کاربر مدیر :")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("national_code")
                                    ->value(old("national_code"))
                                    ->label("کد ملی :")
                                }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                {{
                                    Html::text("user_name")
                                    ->value(old("user_name"))
                                    ->label("نام کاربری :")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("email")
                                    ->value(old("email"))
                                    ->label("ایمیل :")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("password")
                                    ->value(old("password"))
                                    ->label("گذرواژه :")
                                }}
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-4">
                                {{
                                    Html::text("password_confirmation")
                                    ->value(old("password_confirmation"))
                                    ->label("تکرار گذرواژه :")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("mobile")
                                    ->value(old("mobile"))
                                    ->label("شماره همراه :")
                                }}
                            </div>
                            <div class="col-md-4">
                                {{
                                    Html::text("address")
                                    ->value(old("address"))
                                    ->label("آدرس :")
                                }}
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        <div class="float-left">
                            <div class="pull-left">{{ Html::submit()->label('ذخیره') }}</div>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">
                    <strong>لیست کاربران مدیر مرکز : </strong>
                </div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                        <tr>
                            <th></th>
                            <th>ردیف</th>
                            <th>نام مرکز نیکوکاری</th>
                            <th>نام و نام خانوادگی کاربر مدیر</th>
                            <th>کد ملی</th>
                            <th>نام کاربری</th>
                            <th>ایمیل</th>
                            <th>شماره همراه</th>
                            <th>وضعیت</th>
                            <th>حذف</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($users as $user)
                            <tr>
                                <td></td>
                                <td>{{$loop->iteration }}</td>
                                <td>{{$user->charity_id}}</td>
                                <td>{{$user->name}}</td>
                                <td>{{$user->national_code}}</td>
                                <td>{{$user->user_name}}</td>
                                <td>{{$user->email}}</td>
                                <td>{{$user->mobile}}</td>
                                <td>فعال/غیرفعال</td>
                                <td>حذف</td>
                            </tr>
                        @endforeach
                        </tbody>
                    </table>
                </div>
                <div class="card-footer">
                    <div class="float-left">
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> خروجی اکسل</a>
                        <a class="btn btn-outline-info btn-sm" href="#"><i
                                    class="fa fa-edit"></i> چاپ</a>

                    </div>
                </div>
            </div>
        </div>

    </div>

@stop